# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matDiMult <- function(A, B, n_cores) {
    .Call('_JOINTLY_matDiMult', PACKAGE = 'JOINTLY', A, B, n_cores)
}

matTriMult <- function(A, B, C, n_cores) {
    .Call('_JOINTLY_matTriMult', PACKAGE = 'JOINTLY', A, B, C, n_cores)
}

matQuadMult <- function(A, B, C, D, n_cores) {
    .Call('_JOINTLY_matQuadMult', PACKAGE = 'JOINTLY', A, B, C, D, n_cores)
}

